name: 'Bing Paper'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 22 * * *'

jobs:
  bing-paper:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      
      - name: Install requestes
        run: pip install requests

      - name: Get paper
        run: python ./bing.py
      
      - name: Commit
        run: |
          git config --local user.email "15152347277@163.com"
          git config --local user.name "Blackyukun"
          git commit -m "update" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'
