name: 'Bing Paper'

on:
  push:
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      
      - name: Install requestes
        run: pip install requests

      - name: Get paper
        run: python ./bing.py
      
      - name: Commit
        uses: github-actions-x/commit@v2.7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          push-branch: 'main'
          commit-message: 'today paper'
          force-add: 'true'
          files: papers/*
          name: ${{secrets.USERNAME}}
          email: ${{secrets.MAIL_USERNAME}}
